spring:
  profiles:
    active: prod
  application:
    name: AILabCardinal

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.ailab.ailabsystem.model.entity # 别名扫描包
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true

