server:
  port: 8080
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher     # swagger需要开启这个选项

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://ailab-system-datebase.org:3306/ailabsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://172.38.0.3:3306/ailabcardinal?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    #    password: abc123
    password: nfsn520


  redis:
    cluster:
      nodes: 172.38.0.11:6379,172.38.0.12:6379,172.38.0.13:6379 # Redis集群节点
      max-redirects: 3  # 最大重定向数，建议设置为3
    timeout: 3000  # Redis连接超时时间，单位毫秒
    jedis:
      pool:
        max-idle: 100
        max-wait: 1

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1713471338@qq.com
    password: meamkpgfjdegbhcb
    port: 587
    protocol: smtp


mybatis-plus:
  configuration:
    # 配置日记
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#================================================
# 自定义配置
#================================================
custom:
  swagger:
    enable: false

logging:
  file:
    path: /var/log/AiLabCardinal-logging

ailabcardinal:
  version: 1.0.0