server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher     # swagger需要开启这个选项

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://ailab-system-datebase.org:3306/ailabsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/ailabcardinal?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
#    password: abc123
    password: 12345678


  redis:
    host: r-7xv7ctef3xrpmphz49pd.redis.rds.aliyuncs.com
    port: 6379
    database: 2
    username: hf
    password: aLiYun123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    timeout: 10000

mybatis-plus:
  configuration:
    # 配置日记
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#================================================
# 自定义配置
#================================================
custom:
  swagger:
    enable: true
